export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const CHANGE_DATE_FILTER = 'CHANGE_DATE_FILTER'

export const CHANGE_FILTERS = 'CHANGE_FILTERS'